### ISSUE TITLE
Wrong Import of FastChildWatcher

### ISSUE THREAD

**Issue by aristosp** [turpaultn/DESED#60] opened 2022-05-29 08:53 UTC
Greetings, I'm trying to download the real sounds dataset, but for the life of me I can not , because the following error arises:
_cannot import name 'FastChildWatcher' from 'asyncio'_
I'm using pycharm as IDE, with python 3.9 and used the project interpreter to install desed library. asyncio version is 3.4.3
The code is in the following image:
![εικόνα_2022-05-29_115312598](https://user-images.githubusercontent.com/62808962/170860116-5414833e-8a30-45d7-b088-17925d88e36c.png)

**Comment by Dxymiemiemie** [comment] 2022-10-04 02:06
my problem is same as above. Can anyone help us? Thanks!

**Comment by Dxymiemiemie** [comment] 2022-10-07 14:59
> 



> Hi there, Did you try using python 3.8 ? (I did not test python 3.9 yet)

I used python 3,6   based on Windows. I tried on  Ubuntu this problem seems to gone. It is wired..

**Comment by turpaultn** [comment] 2022-10-10 14:12
Ok, then I close this issue, feel free to reopen it if you have more information 😄

**Closed by turpaultn** 2022-10-10 14:12 UTC

**Comment by tp7887** [comment] 2022-10-28 15:39
I think the problem is asyncio.FastChildWatcher isnt compatible with window
when I try on linux it work well while window not
further more asyncio/unix_events.py has FastChildWatcher while asyncio/windows_events.py doesnt have it
just my guessing

**Comment by Harper812** [comment] 2023-07-02 03:48
### Hi there, I just fixed it by commenting this line in download.py. 
environment: Win64_x86
```python
# from asyncio import FastChildWatcher   #comment this line!
import functools
import glob
import inspect
import logging
import os
```
### I found this module not being used.
